files = [
('/Users/nerina/Documents\Adriane_Calaboni_CV.pdf', 159225),
('/Users/nerina/Documents\betweenoper.sql', 459),
('/Users/nerina/Documents\carnetcovid-ana.pdf', 168563),
('/Users/nerina/Documents\carnetcovid-nerida.pdf', 168688),
('/Users/nerina/Documents\CartaPresentacion-Natura2023-NeridaHV.pdf', 154141),
('/Users/nerina/Documents\Certificado_javacoursera.pdf', 321600),
('/Users/nerina/Documents\Certificado_POO1coursera.pdf', 417881),
('/Users/nerina/Documents\circulo-desafio-colisiones.html', 1854),
('/Users/nerina/Documents\countdistinc.sql', 696),
('/Users/nerina/Documents\CURRÍCULUM VITAE_2023-Enero.docx.pdf', 170052),
('/Users/nerina/Documents\CV Nerida HV 2022.docx', 40216),
('/Users/nerina/Documents\CV Nerida HV 2022.pdf', 255361),
('/Users/nerina/Documents\CV Nerida HV 2023.pdf', 177399),
('/Users/nerina/Documents\dateformat.sql', 2284),
('/Users/nerina/Documents\Default.rdp', 0),
('/Users/nerina/Documents\desktop.ini', 402),
('/Users/nerina/Documents\fivegroupfunction.sql', 1725),
('/Users/nerina/Documents\generate_large_files_example.py', 639),
('/Users/nerina/Documents\incondition.sql', 564),
('/Users/nerina/Documents\lab1sql.sql', 1289),
('/Users/nerina/Documents\lab2sql.sql', 1559),
]